# 25 reikningar með numpy

## setup

In [ ]:
import numpy as np
import numpy.linalg as la
from math import pow

a = np.array([ 3, 2, 8])
b = np.array([ 2, 0, 1])
c = np.array([-2, 1, 5])

A = np.array([
    [2,4,7],
    [3,4,8],
    [4,6,9]
])

B = np.array([
    [5,5,5],
    [6,6,6],
    [7,8,9]
])

## 1

### a)

In [4]:
aOut = (a * b) - ((c * (B * b)) / (3 * la.norm(c)))
print(aOut)

[[7.21716124 0.         6.47854845]
 [7.46059349 0.         6.17425814]
 [7.70402573 0.         5.26138721]]


### b)

In [8]:
bOut = 2 * ((A.T) + (B ** 2)) * (a - (2 * b))
print(bOut)

[[ -54  112  348]
 [ -80  160  504]
 [-112  288 1080]]


### c)

In [10]:
cOut1 = la.det(A)
cOut2 = 1 / A # x⁻¹ == 1/x

print(cOut1)
print(cOut2)

10.000000000000002
[[0.5        0.25       0.14285714]
 [0.33333333 0.25       0.125     ]
 [0.25       0.16666667 0.11111111]]


### d)

In [13]:
# hneppi = np.array([A,1])
reiknad = la.solve(A,b)
print(reiknad)

[-2.   1.5  0. ]


### e)

In [14]:
# 10x + 5y = 170
# x + y = 23

hneppi = np.array([[10,5],[1,1]])
utkoma = np.array([170,23])
reiknad = la.solve(hneppi,utkoma)
print(reiknad)

[11. 12.]


## 2

In [18]:
def jafna(n):
    A = np.zeros((n,n))
    b = np.zeros(n)
    for i in range(n-1):
        A[,(j,i)] = [1,(i-j)]

out = jafna(4)
print(out)


LinAlgError: 1-dimensional array given. Array must be at least two-dimensional