In [4]:
import numpy as np
import numpy.linalg as la

A = np.array([
    [0,1,1,1],
    [0,0,1,1],
    [0,0,0,1],
    [0,0,0,0]])

A2 = la.matrix_power(A,2)
A3 = la.matrix_power(A,3)

B = A + A2 + A3
print(A)
print(A2)
print(A3)
print(B)

[[0 1 1 1]
 [0 0 1 1]
 [0 0 0 1]
 [0 0 0 0]]
[[0 0 1 2]
 [0 0 0 1]
 [0 0 0 0]
 [0 0 0 0]]
[[0 0 0 1]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[0 1 2 4]
 [0 0 1 2]
 [0 0 0 1]
 [0 0 0 0]]


In [1]:
import numpy as np
import numpy.linalg as la

b = (0.2, 0.6, 0.8)
d = (0.2, 0.5, 1)   
x0 = np.array([1200, 1000, 800])

A = np.array([
    [0.2,0.6,0.8],
    [0.8,0,0],
    [0,0.5,0]])

x1 = A @ x0
x2 = A @ x1
x100 = la.matrix_power(A,100) @ x0
x200 = la.matrix_power(A,200) @ x0

print(x0)
print(x1)
print(x2)
print(x100)
print(x200)

[1200 1000  800]
[1480.  960.  500.]
[1272. 1184.  480.]
[1339.62264151 1071.69811321  535.8490566 ]
[1339.62264151 1071.69811321  535.8490566 ]
